### ISSUE TITLE
Need tube hardware

### ISSUE THREAD

**Issue by arthurbenemann** [arthurbenemann/arduhoop#2]
Tubes are needed for the hula-hoop:
- [x] spec the tube
- [x] buy the tube

**Comment by arthurbenemann** [comment]
Oops, I closed this one by mistake

**Comment by apaskulin** [comment]
Purchased High-Pressure/Vacuum Polyethylene Tubing from McMaster-Carr in semi-clear white.
ID: 7/8" (22.225mm)
OD: 1" (25.4mm)

http://www.mcmaster.com/#50375k58/=yvufw2
