### ISSUE TITLE
Add logo to PCB

### ISSUE THREAD

**Issue by apaskulin** [arthurbenemann/arduhoop#8]
#7

**Comment by arthurbenemann** [comment]
![image](https://cloud.githubusercontent.com/assets/3289118/14400543/6a099900-fdae-11e5-8227-dc84c5dbabc1.png)
lines are to thin right now (68nm), so they will likely not survive the silkscreen process.

@apaskulin can you thicken them?

**Comment by apaskulin** [comment]
![arduhoop-thick](https://cloud.githubusercontent.com/assets/11339965/14623615/ac98202a-0588-11e6-9f68-e53d76382a29.png)
How's this?

**Comment by arthurbenemann** [comment]
Looks good
![image](https://cloud.githubusercontent.com/assets/3289118/14623654/0e204200-0589-11e6-8128-76de883c975a.png)
